version: '3.1'

services:
  app:
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./main_app:/main_app
    command: sh -c "flask run"
    env_file:
      - ./.env
    depends_on:
      - postgresql

    
  postgresql:
    image: postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - /var/cache/postgres_data:/var/lib/postgresql/data