version: '3.1'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./main_app:/main_app
    command: sh -c "flask run --port=8000 --host=0.0.0.0 --reload"
    env_file:
      - ./.env
    depends_on:
      - postgresql-flask

    
  postgresql-flask:
    image: postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - /var/cache/postgres_flask_data:/var/lib/postgresql/data